#!/usr/bin/env bash

# `exports` is used to provide custom variables.
#
# This file is used as a part of `.shell-env`

# === General ===

export LANG=en_US

# Homebrew:
export HOMEBREW_NO_ANALYTICS=1  # disables statistics that brew collects

# Pagers:
#export LESS="-RF"  # argument to allow less to show colors
#export PAGER='bat'
#export MANPAGER='bat'

# === Version managers ===

# nvm:
export NVM_DIR="$HOME/.nvm"
source "/usr/local/opt/nvm/nvm.sh"

# SDKMAN:
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# JABBA:
export JABBA_DIR="$HOME/.jabba"
[[ -s "$HOME/.jabba/jabba.sh" ]] && source "$HOME/.jabba/jabba.sh"

