#!/usr/bin/env bash

# `exports` is used to provide custom variables.
#
# This file is used as a part of `.shell-env`

# === Version managers ===

# nvm:
export NVM_DIR="$HOME/.nvm"
source "/usr/local/opt/nvm/nvm.sh"
