tap "getantibody/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "antibody"
brew "gdbm"
brew "gettext"
brew "readline"
brew "sqlite"
brew "xz"
brew "awscli@1", link: true
brew "bat"
brew "carthage"
brew "cocoapods"
brew "coreutils"
brew "ctop"
brew "libunistring"
brew "libidn2"
brew "curl"
brew "dnsmasq", restart_service: true
brew "fzf"
brew "git"
brew "htop"
brew "httpie"
brew "jq"
brew "mas"
brew "nvm"
brew "pcre"
brew "postgresql"
brew "rustup-init"
brew "the_silver_searcher"
brew "tig"
brew "vim"
brew "wget"
brew "zsh"
cask "appcleaner"
cask "cleanmymac"
cask "cyberduck"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "grammarly"
cask "handbrake"
cask "iterm2"
cask "jd-gui"
cask "jetbrains-toolbox"
cask "microsoft-teams"
cask "pgadmin4"
cask "postman"
cask "proxyman"
cask "sublime-text"
cask "suspicious-package"
cask "teamviewer"
cask "transmission"
cask "visual-studio-code"
cask "vlc"
cask "wakeonlan"
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "The Unarchiver", id: 425424353
mas "WakeOnCommand", id: 1484204619
mas "Xcode", id: 497799835
