tap "getantibody/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "stripe/stripe-cli"
brew "antibody"
brew "bat"
brew "carthage"
brew "coreutils"
brew "gettext"
brew "libunistring"
brew "readline"
brew "libidn2"
brew "cask"
brew "cdrtools"
brew "ctop"
brew "curl"
brew "dive"
brew "fzf"
brew "gdbm"
brew "gh"
brew "git"
brew "htop"
brew "xz"
brew "httpie"
brew "kind"
brew "mas"
brew "nvm"
brew "pcre"
brew "postgresql"
brew "pyenv"
brew "rustup-init"
brew "the_silver_searcher"
brew "tig"
brew "vegeta"
brew "vim"
brew "wget"
brew "zsh"
brew "stripe/stripe-cli/stripe"
cask "adobe-acrobat-reader"
cask "appcleaner"
cask "cleanmymac"
cask "cyberduck"
cask "discord"
cask "docker"
cask "firefox"
cask "gimp"
cask "google-chrome"
cask "gpg-suite"
cask "grammarly"
cask "handbrake"
cask "iina"
cask "iterm2"
cask "jd-gui"
cask "jetbrains-toolbox"
cask "keystore-explorer"
cask "microsoft-teams"
cask "pgadmin4"
cask "postman"
cask "proxyman"
cask "sublime-text"
cask "suspicious-package"
cask "teamviewer"
cask "transmission"
cask "visual-studio-code"
cask "visualvm"
cask "vlc"
cask "wakeonlan"
mas "Disk Space Analyzer Free", id: 446243721
mas "Duplicate File Finder", id: 1032755628
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "The Unarchiver", id: 425424353
mas "WakeOnCommand", id: 1484204619
