#!/usr/bin/env bash

# This file contains settings for mac which makes me happy.
# It is not a full list.

echo 'Configuring MacOS...'

# === General ===

# Maximize windows on double clicking them:
defaults write -g AppleActionOnDoubleClick 'Maximize'

# Require password immediately after sleep or screen saver begins
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

# === Dock ===

# Show indicator lights for open apps in Dock:
defaults write com.apple.dock show-process-indicators -bool true

# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# === Finder ===

# Show Finder path bar:
defaults write com.apple.finder ShowPathbar -bool true

# Show file extensions in Finder:
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Display full POSIX path as Finder window title
defaults write com.apple.finder _FXShowPosixPathInTitle -bool false

# === iTerm2 ===

# Load preferences from file
defaults write com.googlecode.iterm2 PrefsCustomFolder -string "~/.dotfiles/applications/iterm2/"
defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true

#defaults write com.apple.finder AppleShowAllFiles YES

# This line deactivates rubber scrolling:
# http://osxdaily.com/2012/05/10/disable-elastic-rubber-band-scrolling-in-mac-os-x/
#defaults write -g NSScrollViewRubberbanding -int 0

#defaults write -g AppleActionOnDoubleClick 'Maximize'
#defaults write -g AppleEnableSwipeNavigateWithScrolls -int 0
#defaults write -g AppleInterfaceStyle 'Dark'

# Restarting apps:
echo 'Restarting apps...'
killall Finder
killall Dock

echo 'Done!'
