#!/usr/bin/env zsh

# `shell_env.sh` is a main file for any general-case utils.
#
# This file is used as a source file for zsh.

# === Plugin management ===

# antibody bundle < "$HOME/.antibody" > "$HOME/.zsh-plugins"
# source "$HOME/.zsh-plugins"


# === Shell parts ===

source "$HOME/.shell/exports"
source "$HOME/.shell/aliases"
source "$HOME/.shell/functions"
source "$HOME/.shell/external"

export PATH="$PATH:$HOME/.shell/bin"
export PATH="$PATH:$HOME/.shell/bin-local"

SOURCED_FILES=$(find "$HOME/.shell/source.d" -type f -path "*\.sh" -exec basename -a {} \;)
for SOURCED_FILE in $(echo "${SOURCED_FILES}"); do
  # shellcheck source=$HOME/.shell/source.d/kubeswitch_cleanup_handler_zsh.sh
  source "$HOME/.shell/source.d/$SOURCED_FILE"
done
unset SOURCED_FILES SOURCED_FILE

# === Local variables and overrides ===

if [[ -f "$HOME/.shell-env-local" ]]; then
  source "$HOME/.shell-env-local"
fi
